package notices

import (
	"fmt"
	"maps"
	"slices"
	"strings"
	"unicode/utf8"

	"github.com/ovineko/schepherd/internal/fault"
	"github.com/ovineko/schepherd/internal/publisher/state"
	"github.com/ovineko/schepherd/tools/release/internal/licenses"
)

// inputs is everything the notices are rendered from.
type inputs struct {
	data  *data
	rules map[string]policyRule
	// state is the catalog state; nil before the first publication.
	state   *state.State
	client  []licenses.Component
	targets []licenses.Target
}

const intro = `# Third-party notices

Schepherd's own source code is licensed under the MIT License (see
[LICENSE](LICENSE)). The components below keep their own licenses.

This file covers what Schepherd distributes: the ` + "`schepherd`" + ` client binary and the schemas of
the catalog. What only maintainers, CI and tests use (` + "`schepherd-publisher`" + `, the tools pinned in
` + "`tools/pins`" + `, container images, Python build and test requirements) is never distributed and is
not listed here; the license of an image's main project would not describe everything the image
contains anyway.

This file is generated by ` + "`go run ./tools/release notices generate`" + `; do not edit it by hand.
` + "`go run ./tools/release notices check`" + ` fails when it no longer matches its inputs: the Go modules
the client links for every release target, ` + "`tools/release/notices.toml`, `sources/licenses.toml`" + `
and ` + "`catalog/state.json`" + `. The weekly catalog job commits it together with every catalog
revision it records.
`

const clientIntro = `## Linked into the ` + "`schepherd`" + ` client binary

The full license, notice and patent texts of every component in this table are in
[THIRD_PARTY_LICENSES.txt](THIRD_PARTY_LICENSES.txt), which ships next to the binary in every
release archive and every npm platform package. The table lists what ` + "`go list -deps`" + ` reports
with the toolchain named in ` + "`go.mod`" + `; each license is identified from the component's
license file.

Release targets: %s.
`

const clientOutro = `The client contains no JSON Schema engine and no schema content.
`

const schemasIntro = `## Schemas distributed through the catalog

Schemas are not part of this repository and are not covered by Schepherd's license. Each schema
artifact carries a notice layer with the full license and notice texts that apply to its content,
and each catalog entry records its source, source digest and license. The license policy for
published schemas is [` + "`sources/licenses.toml`" + `](sources/licenses.toml); see
[Publishing](docs/publishing.md#licenses).
`

const noCatalog = "No catalog has been published yet: `catalog/state.json` does not exist.\n"

// render classifies the licenses and writes the notices. It fails on a
// license the classifier does not recognize and on data that does not match
// what was collected.
func render(in *inputs) ([]byte, error) {
	var b strings.Builder

	b.WriteString(intro)

	if err := renderClient(&b, in); err != nil {
		return nil, err
	}

	if err := renderSchemas(&b, in); err != nil {
		return nil, err
	}

	return []byte(b.String()), nil
}

func renderClient(b *strings.Builder, in *inputs) error {
	names := make([]string, 0, len(in.targets))
	for _, t := range in.targets {
		names = append(names, t.String())
	}

	rows, err := moduleRows(in.client, in.targets)
	if err != nil {
		return err
	}

	b.WriteString("\n" + fmt.Sprintf(clientIntro, strings.Join(names, ", ")) + "\n")
	b.WriteString(table([]string{"Module", "Version", "License"}, rows))
	b.WriteString("\n" + clientOutro)

	return nil
}

func moduleRows(components []licenses.Component, all []licenses.Target) ([][]string, error) {
	rows := make([][]string, 0, len(components))

	for _, c := range components {
		cell := code(c.Name)
		if c.Name == licenses.Stdlib {
			cell = licenses.Stdlib
		}

		license, err := componentLicense(c.Files)
		if err != nil {
			return nil, fault.Wrap(fault.Internal, err, "%s %s", c.Name, c.Version)
		}

		if remark := scope(c.Targets, all); remark != "" {
			cell += " (" + remark + ")"
		}

		rows = append(rows, []string{cell, c.Version, license})
	}

	return rows, nil
}

func renderSchemas(b *strings.Builder, in *inputs) error {
	if _, err := schemaStoreLicense(in.rules, in.data.SchemaStore); err != nil {
		return err
	}

	b.WriteString("\n" + schemasIntro + "\n")

	st := in.state
	if st == nil {
		b.WriteString(noCatalog)

		return nil
	}

	groups, err := schemaGroups(st, in.rules, in.data.SchemaStore)
	if err != nil {
		return err
	}

	count := len(st.Entries())

	from := "the local source " + code(st.Source.Name)
	if st.Source.Kind == state.KindSchemaStore {
		from = "the SchemaStore catalog at commit " + code(st.Source.Commit)
	}

	fmt.Fprintf(b, "Catalog revision %s (manifest %s), prepared from %s, lists %d %s. Each schema is listed under "+
		"every source of its content: its own document and every dependency bundled into it.\n",
		code(st.Catalog.Revision), code(st.Catalog.Digest), from, count, plural(count, "schema", "schemas"))

	for _, g := range groups {
		b.WriteString("\n### " + g.heading + "\n")

		for _, p := range g.text {
			b.WriteString("\n" + p + "\n")
		}

		if len(g.details) > 0 {
			b.WriteString("\nLicense detected from " + joinWords(g.details) + ".\n")
		}

		fmt.Fprintf(b, "\n%d %s:\n\n", len(g.ids), plural(len(g.ids), "schema", "schemas"))

		for _, id := range g.ids {
			b.WriteString("- " + code(id) + "\n")
		}
	}

	return nil
}

var osNames = map[string]string{"darwin": "macOS", "linux": "Linux", "windows": "Windows"}

// scope describes the targets of a component linked into only some of all
// the targets: whole operating systems by name, otherwise every target.
func scope(targets, all []licenses.Target) string {
	if len(targets) == len(all) {
		return ""
	}

	total, linked := map[string]int{}, map[string]int{}

	for _, t := range all {
		total[t.GOOS]++
	}

	for _, t := range targets {
		linked[t.GOOS]++
	}

	var systems []string

	for _, goos := range slices.Sorted(maps.Keys(linked)) {
		name, known := osNames[goos]
		if !known || linked[goos] != total[goos] {
			names := make([]string, 0, len(targets))
			for _, t := range targets {
				names = append(names, t.String())
			}

			return strings.Join(names, ", ") + " only"
		}

		systems = append(systems, name)
	}

	return joinWords(systems) + " builds only"
}

// table renders a Markdown table with padded columns.
func table(header []string, rows [][]string) string {
	widths := make([]int, len(header))

	for _, row := range append([][]string{header}, rows...) {
		for i, cell := range row {
			widths[i] = max(widths[i], utf8.RuneCountInString(cell), 3)
		}
	}

	line := func(cells []string) string {
		padded := make([]string, len(cells))
		for i, cell := range cells {
			padded[i] = cell + strings.Repeat(" ", widths[i]-utf8.RuneCountInString(cell))
		}

		return "| " + strings.Join(padded, " | ") + " |\n"
	}

	rules := make([]string, len(header))
	for i, w := range widths {
		rules[i] = strings.Repeat("-", w)
	}

	var b strings.Builder

	b.WriteString(line(header))
	b.WriteString(line(rules))

	for _, row := range rows {
		b.WriteString(line(row))
	}

	return b.String()
}
